spring.application.name=spring-boot-essencials

# Configuração Local do MySQL (ajustado para seu banco 'HeroldBloom')
spring.datasource.url=jdbc:mysql://localhost:3306/HeroldBloom?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA & Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Enums
spring.jackson.mapper.accept-case-insensitive-enums=true
spring.mvc.format.enum-case-sensitive=false

# Segredo do JWT
api.security.token.secret=${JWT_SECRET:croche-secret-key-loja-heroldbloom-spring-boot-2026}